psgcwd_server/config/routes.rb
Rails.application.routes.draw do
  get 'admin/dashboard'
  resources :projects
  resources :monthperiods
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'admin/*missing', to: 'admin#dashboard' # ReactJS router
end

psgcwd_server/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

psgcwd_server/app/models/guidable.rb
require 'securerandom'

module Guidable
  extend ActiveSupport::Concern

  included do
    before_create :do_guid
  end


  def do_guid
    self.guid = SecureRandom.uuid if guid.blank?
  end
end

# [ ] %TODO https://stackoverflow.com/questions/45445744/how-to-create-a-common-after-create-callback-for-all-models

psgcwd_server/app/models/monthperiod.rb
class Monthperiod < ApplicationRecord
  include Guidable
  include Sluggable

  self.set_target_fields :period_year, :month_number
end

psgcwd_server/app/models/project.rb
class Project < ApplicationRecord
  include Guidable
  include Sluggable

  belongs_to :startdate, class_name: :Monthperiod
  belongs_to :enddate, class_name: :Monthperiod

  def to_param  # overridden
    slug
  end

  self.set_target_fields :ptitle
end

psgcwd_server/app/models/sluggable.rb
module Sluggable
  extend ActiveSupport::Concern

  included do
    before_create :slugify
    class_attribute :target_fields
  end

  def slugify
    str = self.target_fields.reduce('') { |a, s| a + "-" + self[s].to_s } 
    self.slug = str.parameterize
  end

  # methods defined here are going to extend the class, not the instance of it
  module ClassMethods
    def set_target_fields(*fields)
      self.target_fields = fields
    end
  end
end

# [ ] %TODO - write unit test
# [ ] %TODO https://stackoverflow.com/questions/45445744/how-to-create-a-common-after-create-callback-for-all-models

# move to concern? - https://stackoverflow.com/questions/46422576/how-do-i-reference-model-attributes-in-module-instance-methods-in-ror-5

# https://stackoverflow.com/questions/35271911/set-class-variable-from-module
# https://stackoverflow.com/questions/15773552/ruby-class-instance-variable-vs-class-variable
# 
#  => http://www.railstips.org/blog/archives/2006/11/18/class-and-instance-variables-in-ruby/
#  https://stackoverflow.com/questions/26517349/are-rails-module-instance-variables-available-to-other-classes
#  https://stackoverflow.com/questions/2567956/rails-class-self
# 
# 
#  => https://stackoverflow.com/questions/14541823/how-to-use-concerns-in-rails-4

psgcwd_server/app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def dashboard
  end
end

psgcwd_server/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

psgcwd_server/app/controllers/monthperiods_controller.rb
class MonthperiodsController < ApplicationController
  before_action :set_monthperiod, only: [:show, :edit, :update, :destroy]

  # GET /monthperiods
  # GET /monthperiods.json
  def index
    @monthperiods = Monthperiod.all
  end

  # GET /monthperiods/1
  # GET /monthperiods/1.json
  def show
  end

  # GET /monthperiods/new
  def new
    @monthperiod = Monthperiod.new
  end

  # GET /monthperiods/1/edit
  def edit
  end

  # POST /monthperiods
  # POST /monthperiods.json
  def create
    @monthperiod = Monthperiod.new(monthperiod_params)

    respond_to do |format|
      if @monthperiod.save
        format.html { redirect_to @monthperiod, notice: 'Monthperiod was successfully created.' }
        format.json { render :show, status: :created, location: @monthperiod }
      else
        format.html { render :new }
        format.json { render json: @monthperiod.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /monthperiods/1
  # PATCH/PUT /monthperiods/1.json
  def update
    respond_to do |format|
      if @monthperiod.update(monthperiod_params)
        format.html { redirect_to @monthperiod, notice: 'Monthperiod was successfully updated.' }
        format.json { render :show, status: :ok, location: @monthperiod }
      else
        format.html { render :edit }
        format.json { render json: @monthperiod.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /monthperiods/1
  # DELETE /monthperiods/1.json
  def destroy
    @monthperiod.destroy
    respond_to do |format|
      format.html { redirect_to monthperiods_url, notice: 'Monthperiod was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_monthperiod
      @monthperiod = Monthperiod.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def monthperiod_params
      params.require(:monthperiod).permit(:guid, :slug, :period_year, :month_number, :start_date, :end_date)
    end
end

psgcwd_server/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = Project.all
  end

  def show
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_project
      @project = Project.find_by(slug: params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:guid, :slug, :ptitle, :psubtitle, :body, :client, :startdate_id, :enddate_id)
    end
end

psgcwd_server/app/helpers/admin_helper.rb
module AdminHelper
end

psgcwd_server/app/helpers/application_helper.rb
module ApplicationHelper
end

psgcwd_server/app/helpers/monthperiods_helper.rb
module MonthperiodsHelper
end

psgcwd_server/app/helpers/projects_helper.rb
module ProjectsHelper
end

psgcwd_server/app/views/admin/dashboard.html.erb
<h1>Admin#dashboard</h1>
<p>Find me in app/views/admin/dashboard.html.erb</p>
<%= react_component("AdminHome", { greeting: "Hello from react-rails." }) %>

psgcwd_server/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PsgcwdServer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top" id="sideNav">
      <a class="navbar-brand js-scroll-trigger" href="#page-top">
        <span class="d-block d-lg-none">Clarence Taylor</span>
        <span class="d-none d-lg-block">
          <img class="img-fluid img-profile rounded-circle mx-auto mb-2" src="img/profile.jpg" alt="">
        </span>
      </a>
      <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger active" href="#about">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#experience">Experience</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#education">Education</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#skills">Skills</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#interests">Interests</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#awards">Awards</a>
          </li>
        </ul>
      </div>
    </nav>
    <%= yield %>

  </body>
</html>

psgcwd_server/app/views/monthperiods/_form.html.erb
<%= form_with(model: monthperiod, local: true) do |form| %>
  <% if monthperiod.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(monthperiod.errors.count, "error") %> prohibited this monthperiod from being saved:</h2>

      <ul>
        <% monthperiod.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :guid %>
    <%= form.text_field :guid %>
  </div>

  <div class="field">
    <%= form.label :slug %>
    <%= form.text_field :slug %>
  </div>

  <div class="field">
    <%= form.label :period_year %>
    <%= form.text_field :period_year %>
  </div>

  <div class="field">
    <%= form.label :month_number %>
    <%= form.number_field :month_number %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_select :start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.date_select :end_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

psgcwd_server/app/views/monthperiods/edit.html.erb
<h1>Editing Monthperiod</h1>

<%= render 'form', monthperiod: @monthperiod %>

<%= link_to 'Show', @monthperiod %> |
<%= link_to 'Back', monthperiods_path %>

psgcwd_server/app/views/monthperiods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Monthperiods</h1>

<table>
  <thead>
    <tr>
      <th>Guid</th>
      <th>Slug</th>
      <th>Period year</th>
      <th>Month number</th>
      <th>Start date</th>
      <th>End date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @monthperiods.each do |monthperiod| %>
      <tr>
        <td><%= monthperiod.guid %></td>
        <td><%= monthperiod.slug %></td>
        <td><%= monthperiod.period_year %></td>
        <td><%= monthperiod.month_number %></td>
        <td><%= monthperiod.start_date %></td>
        <td><%= monthperiod.end_date %></td>
        <td><%= link_to 'Show', monthperiod %></td>
        <td><%= link_to 'Edit', edit_monthperiod_path(monthperiod) %></td>
        <td><%= link_to 'Destroy', monthperiod, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Monthperiod', new_monthperiod_path %>

psgcwd_server/app/views/monthperiods/new.html.erb
<h1>New Monthperiod</h1>

<%= render 'form', monthperiod: @monthperiod %>

<%= link_to 'Back', monthperiods_path %>

psgcwd_server/app/views/monthperiods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Guid:</strong>
  <%= @monthperiod.guid %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @monthperiod.slug %>
</p>

<p>
  <strong>Period year:</strong>
  <%= @monthperiod.period_year %>
</p>

<p>
  <strong>Month number:</strong>
  <%= @monthperiod.month_number %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @monthperiod.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @monthperiod.end_date %>
</p>

<%= link_to 'Edit', edit_monthperiod_path(@monthperiod) %> |
<%= link_to 'Back', monthperiods_path %>

psgcwd_server/app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :guid %>
    <%= form.text_field :guid %>
  </div>

  <div class="field">
    <%= form.label :slug %>
    <%= form.text_field :slug %>
  </div>

  <div class="field">
    <%= form.label :ptitle %>
    <%= form.text_field :ptitle %>
  </div>

  <div class="field">
    <%= form.label :psubtitle %>
    <%= form.text_field :psubtitle %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :client %>
    <%= form.text_field :client %>
  </div>

  <div class="field">
    <%= form.label :startdate_id %>
    <%= form.number_field :startdate_id %>
  </div>

  <div class="field">
    <%= form.label :enddate_id %>
    <%= form.number_field :enddate_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

psgcwd_server/app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

psgcwd_server/app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<div class="container">
    <div class="row">
        <div class="col-sm">
            One of three columns
        </div>
        <div class="col-sm">
            One of three columns
        </div>
        <div class="col-sm">
            One of three columns
        </div>
    </div>
</div>

<table>
    <thead>
        <tr>
            <th>Guid</th>
            <th>Slug</th>
            <th>Ptitle</th>
            <th>Psubtitle</th>
            <th>Body</th>
            <th>Client</th>
            <th>Startdate</th>
            <th>Enddate</th>
            <th colspan="3"></th>
        </tr>
    </thead>

    <tbody>
        <% @projects.each do |project| %>
            <tr>
                <td><%= project.guid %></td>
                <td><%= project.slug %></td>
                <td><%= project.ptitle %></td>
                <td><%= project.psubtitle %></td>
                <td><%= project.body %></td>
                <td><%= project.client %></td>
                <td><%= project.startdate_id %></td>
                <td><%= project.enddate_id %></td>
                <td><%= link_to 'Show', project %></td>
                <td><%= link_to 'Edit', edit_project_path(project) %></td>
                <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
        <% end %>
    </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

psgcwd_server/app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

psgcwd_server/app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Guid:</strong>
  <%= @project.guid %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @project.slug %>
</p>

<p>
  <strong>Ptitle:</strong>
  <%= @project.ptitle %>
</p>

<p>
  <strong>Psubtitle:</strong>
  <%= @project.psubtitle %>
</p>

<p>
  <strong>Body:</strong>
  <%= @project.body %>
</p>

<p>
  <strong>Client:</strong>
  <%= @project.client %>
</p>

<p>
  <strong>Startdate:</strong>
  <%= @project.startdate_id %>
</p>

<p>
  <strong>Enddate:</strong>
  <%= @project.enddate_id %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>